m1,n1=map(int,input("Enter !st line").split(' '))
m2,n2=map(int,input("Enter 2nd line").split(' '))
m3,n3=map(int,input("Enter 3rd line").split(' '))
if (m1==m2 and m2==m3) or(n1==n2 and n2==n3) or (abs(m1-m2)==abs(m2-m3) and abs(n1-n2)==abs(n2-n3)):print("yes")
else:print("no")
